### ISSUE TITLE
mention DSP.jl

### ISSUE THREAD

**Issue by bjarthur** [platawiec/Unwrap.jl#2]
might want to mention in your README there is similar functionality (for 1D) in https://github.com/JuliaDSP/DSP.jl/blob/8570a71120e67e7790a968e9ab4c8ee3696ae784/src/util.jl#L54-L66

better yet, maybe combine forces and make a PR there?  or move this package into the Julia DSP org so it's easier to find?

**Comment by platawiec** [comment]
Yup, that's the plan! I want to do some profiling before submitting a PR. Until then I'll add to the README.

**Comment by platawiec** [comment]
I've made the major fix I wanted to, I'll be submitting the PR to Julia DSP in the near future.
